/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Box, BoxInterface } from "../Box";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "ValueChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "retrieve",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "store",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061032a806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80632e64cec1146100465780636057361d14610064578063fe4b84df14610080575b600080fd5b61004e61009c565b60405161005b9190610258565b60405180910390f35b61007e600480360381019061007991906101dd565b6100a6565b005b61009a600480360381019061009591906101dd565b6100e7565b005b6000600154905090565b806001819055507f93fe6d397c74fdf1402a8b72e47b68512f0510d7b98a4bc4cbdf6ac7108b3c59816040516100dc9190610258565b60405180910390a150565b600060019054906101000a900460ff168061010d575060008054906101000a900460ff16155b61014c576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161014390610238565b60405180910390fd5b60008060019054906101000a900460ff16159050801561019c576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b8160018190555080156101c45760008060016101000a81548160ff0219169083151502179055505b5050565b6000813590506101d7816102dd565b92915050565b6000602082840312156101ef57600080fd5b60006101fd848285016101c8565b91505092915050565b6000610213602e83610273565b915061021e8261028e565b604082019050919050565b61023281610284565b82525050565b6000602082019050818103600083015261025181610206565b9050919050565b600060208201905061026d6000830184610229565b92915050565b600082825260208201905092915050565b6000819050919050565b7f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160008201527f647920696e697469616c697a6564000000000000000000000000000000000000602082015250565b6102e681610284565b81146102f157600080fd5b5056fea2646970667358221220e0199b6060d20deabc40a09e53fc32399ef8bba6fa7ba1492f109e6f0b99547264736f6c63430008040033";

export class Box__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Box> {
    return super.deploy(overrides || {}) as Promise<Box>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Box {
    return super.attach(address) as Box;
  }
  connect(signer: Signer): Box__factory {
    return super.connect(signer) as Box__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BoxInterface {
    return new utils.Interface(_abi) as BoxInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Box {
    return new Contract(address, _abi, signerOrProvider) as Box;
  }
}
