/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as draftIerc1822UpgradeableSol from "./draft-IERC1822Upgradeable.sol";
export { IERC1967Upgradeable__factory } from "./IERC1967Upgradeable__factory";
