/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as itManTokenSol from "./ITManToken.sol";

export type { itManTokenSol };
export type { Box } from "./Box";
export type { BoxV2 } from "./BoxV2";
export type { Greeter } from "./Greeter";
