/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

import type {
  NoncesUpgradeable,
  NoncesUpgradeableInterface,
} from "../../../../@openzeppelin/contracts-upgradeable/utils/NoncesUpgradeable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "currentNonce",
        type: "uint256",
      },
    ],
    name: "InvalidAccountNonce",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "nonces",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class NoncesUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): NoncesUpgradeableInterface {
    return new utils.Interface(_abi) as NoncesUpgradeableInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): NoncesUpgradeable {
    return new Contract(address, _abi, signerOrProvider) as NoncesUpgradeable;
  }
}
