/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20PausableUpgradeable__factory } from "./ERC20PausableUpgradeable__factory";
export { ERC20PermitUpgradeable__factory } from "./ERC20PermitUpgradeable__factory";
