/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

import type {
  ERC1967UpgradeUpgradeable,
  ERC1967UpgradeUpgradeableInterface,
} from "../../../../../@openzeppelin/contracts-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "previousAdmin",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "AdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "beacon",
        type: "address",
      },
    ],
    name: "BeaconUpgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
];

export class ERC1967UpgradeUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): ERC1967UpgradeUpgradeableInterface {
    return new utils.Interface(_abi) as ERC1967UpgradeUpgradeableInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ERC1967UpgradeUpgradeable {
    return new Contract(address, _abi, signerOrProvider) as ERC1967UpgradeUpgradeable;
  }
}
