/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc1822Sol from "./draft-IERC1822.sol";
export type { draftIerc1822Sol };
import type * as draftIerc6093Sol from "./draft-IERC6093.sol";
export type { draftIerc6093Sol };
export type { IERC5267 } from "./IERC5267";
