/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

import type {
  PausableUpgradeable,
  PausableUpgradeableInterface,
} from "../../../../@openzeppelin/contracts-upgradeable/security/PausableUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PausableUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): PausableUpgradeableInterface {
    return new utils.Interface(_abi) as PausableUpgradeableInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): PausableUpgradeable {
    return new Contract(address, _abi, signerOrProvider) as PausableUpgradeable;
  }
}
