/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as draftIerc1822UpgradeableSol from "./draft-IERC1822Upgradeable.sol";

export type { draftIerc1822UpgradeableSol };
