/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20PausableUpgradeable } from "./ERC20PausableUpgradeable";
export type { ERC20PermitUpgradeable } from "./ERC20PermitUpgradeable";
