name: Build

on: push

jobs:
  build-web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Check out code
        uses: actions/checkout@v4.4.0

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.20.8

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run build
        run: |
          pnpm clean
          pnpm build
